!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.2.0/C4_Container.puml
!global $NK_DIAGRAM_TYPE = "container"
!include https://raw.githubusercontent.com/Nykredit/C4-PlantUML/production/C4_Nykredit.puml
